"""The Alembic revision reproduces create_all and stays aligned with the ORM."""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic.util import AutogenerateDiffsDetected
from app.config import get_settings
from app.db import init_db, prepare_schema, reset_engine
from app.migrate import ORM_TABLES, alembic_config, apply_migrations, uses_alembic
from app.models.orm import Base
from sqlalchemy import create_engine, inspect, text

EXPECTED_TABLES = {
    "tickets",
    "claims",
    "graph_edges",
    "action_cards",
    "jobs",
    "transcript_pointers",
    "import_audit",
}


@pytest.fixture
def isolated(tmp_path, monkeypatch):
    db = tmp_path / "schema.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite+pysqlite:///{db}")
    monkeypatch.setenv("REDIS_OPTIONAL", "true")
    monkeypatch.setenv("SEED_ON_STARTUP", "false")
    get_settings.cache_clear()
    reset_engine()
    yield db
    reset_engine()
    get_settings.cache_clear()


def _engine(db: Path):
    return create_engine(f"sqlite+pysqlite:///{db}", future=True)


def _schema(engine) -> dict:
    """Dialect-agnostic dump: tables, columns, pks, unique cols, non-unique indexes."""
    insp = inspect(engine)
    out: dict = {}
    for name in sorted(insp.get_table_names()):
        if name == "alembic_version":
            continue
        cols = []
        for col in insp.get_columns(name):
            cols.append(
                {
                    "name": col["name"],
                    "type": type(col["type"]).__name__,
                    "nullable": col["nullable"],
                }
            )
        pk = list(insp.get_pk_constraint(name).get("constrained_columns") or [])
        unique: set[tuple] = set()
        nonunique: set[tuple] = set()
        for ix in insp.get_indexes(name):
            key = tuple(ix["column_names"])
            if ix["unique"]:
                unique.add(key)
            else:
                nonunique.add(key)
        for uq in insp.get_unique_constraints(name):
            unique.add(tuple(uq["column_names"]))
        out[name] = {
            "cols": cols,
            "pk": pk,
            "unique": sorted(unique),
            "indexes": sorted(nonunique),
        }
    return out


def test_single_alembic_head():
    from alembic.script import ScriptDirectory

    heads = ScriptDirectory.from_config(alembic_config()).get_heads()
    assert heads == ["33f2fa9884a2"]


def test_orm_table_set_is_the_locked_seven():
    assert set(ORM_TABLES) == EXPECTED_TABLES
    assert set(Base.metadata.tables) == EXPECTED_TABLES


def test_uses_alembic_only_for_postgres():
    assert uses_alembic("postgresql+psycopg2://callparity:x@postgres:5432/callparity")
    assert uses_alembic("postgresql://callparity:x@postgres:5432/callparity")
    assert uses_alembic("postgres://callparity:x@localhost/callparity")
    assert not uses_alembic("sqlite+pysqlite:///./callparity.db")
    assert not uses_alembic("sqlite:///./callparity.db")


def test_prepare_schema_sqlite_uses_create_all(isolated):
    prepare_schema()
    engine = _engine(isolated)
    names = set(inspect(engine).get_table_names())
    engine.dispose()
    assert EXPECTED_TABLES <= names
    assert "alembic_version" not in names


def test_migration_schema_matches_create_all(tmp_path, monkeypatch):
    created = tmp_path / "create_all.db"
    migrated = tmp_path / "migrated.db"

    created_engine = create_engine(f"sqlite+pysqlite:///{created}", future=True)
    Base.metadata.create_all(bind=created_engine)
    created_schema = _schema(created_engine)
    created_engine.dispose()

    monkeypatch.setenv("DATABASE_URL", f"sqlite+pysqlite:///{migrated}")
    get_settings.cache_clear()
    reset_engine()
    assert apply_migrations() == "upgrade"
    migrate_engine = _engine(migrated)
    migrated_schema = _schema(migrate_engine)
    with migrate_engine.connect() as conn:
        version = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
    migrate_engine.dispose()
    reset_engine()
    get_settings.cache_clear()

    assert created_schema == migrated_schema
    assert version
    assert set(migrated_schema) == EXPECTED_TABLES


def test_migrated_db_has_no_autogenerate_drift(isolated):
    apply_migrations()
    from alembic.command import check

    try:
        check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"migration drifted from ORM: {exc}")


def test_stamped_create_all_has_no_autogenerate_drift(isolated):
    init_db()
    assert apply_migrations() == "stamp"
    from alembic.command import check

    try:
        check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"create_all drifted from ORM: {exc}")


def test_apply_migrations_stamps_complete_create_all_schema(isolated):
    init_db()
    assert apply_migrations() == "stamp"
    assert apply_migrations() == "upgrade"
    engine = _engine(isolated)
    names = set(inspect(engine).get_table_names())
    with engine.connect() as conn:
        tickets = conn.execute(text("SELECT count(*) FROM tickets")).scalar()
    engine.dispose()
    assert "alembic_version" in names
    assert EXPECTED_TABLES <= names
    assert tickets == 0


def test_apply_migrations_is_idempotent(isolated):
    assert apply_migrations() == "upgrade"
    assert apply_migrations() == "upgrade"
    engine = _engine(isolated)
    assert set(inspect(engine).get_table_names()) - {"alembic_version"} == EXPECTED_TABLES
    engine.dispose()


def test_apply_migrations_rejects_partial_schema(isolated):
    engine = _engine(isolated)
    with engine.begin() as conn:
        conn.execute(text("CREATE TABLE tickets (id VARCHAR(64) PRIMARY KEY)"))
    engine.dispose()
    with pytest.raises(RuntimeError, match="partial schema"):
        apply_migrations()


def test_seed_converges_on_migrated_schema(isolated):
    assert apply_migrations() == "upgrade"
    from seed_demo_data import seed

    seed()
    seed()
    engine = _engine(isolated)
    with engine.connect() as conn:
        ids = sorted(row[0] for row in conn.execute(text("SELECT id FROM tickets")))
    engine.dispose()
    assert ids == ["FR-1842", "FR-1888", "FR-1900"]
