"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-28 12:24:40.712790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_cards",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_cards_ticket_id"), ["ticket_id"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("source_party", sa.String(length=8), nullable=False),
        sa.Column("predicate", sa.String(length=128), nullable=False),
        sa.Column("entity_ids", sa.JSON(), nullable=False),
        sa.Column("slot", sa.JSON(), nullable=False),
        sa.Column("polarity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_span", sa.Text(), nullable=False),
        sa.Column("call_run_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_ticket_id"), ["ticket_id"], unique=False)

    op.create_table(
        "graph_edges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("hypothesis_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("a_span", sa.Text(), nullable=False),
        sa.Column("b_span", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("predicate", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_edges_ticket_id"), ["ticket_id"], unique=False)

    op.create_table(
        "import_audit",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("call_id_a", sa.String(length=128), nullable=False),
        sa.Column("call_id_b", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_audit_actor"), ["actor"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_audit_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_audit_ticket_id"), ["ticket_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=False),
        sa.Column("telemetry", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_jobs_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_jobs_ticket_id"), ["ticket_id"], unique=False)

    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=128), nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("parties", sa.JSON(), nullable=False),
        sa.Column("sla_usd_per_hour", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transcript_pointers",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("sha256"),
    )
    with op.batch_alter_table("transcript_pointers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transcript_pointers_ticket_id"), ["ticket_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_pointers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_pointers_ticket_id"))

    op.drop_table("transcript_pointers")
    op.drop_table("tickets")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_ticket_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_idempotency_key"))

    op.drop_table("jobs")
    with op.batch_alter_table("import_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_audit_ticket_id"))
        batch_op.drop_index(batch_op.f("ix_import_audit_job_id"))
        batch_op.drop_index(batch_op.f("ix_import_audit_actor"))

    op.drop_table("import_audit")
    with op.batch_alter_table("graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_edges_ticket_id"))

    op.drop_table("graph_edges")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_ticket_id"))

    op.drop_table("claims")
    with op.batch_alter_table("action_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_cards_ticket_id"))

    op.drop_table("action_cards")
    # ### end Alembic commands ###
